
import re, unicodedata

def _norm(text: str) -> str:
    if text is None:
        return ""
    s = unicodedata.normalize("NFKD", str(text)).encode("ascii", "ignore").decode("ascii")
    s = s.lower().strip()
    s = s.replace(".", " ")
    s = re.sub(r"[^a-z0-9/&,+\-\s()']", " ", s)
    s = re.sub(r"\s+", " ", s)
    s = s.replace("st ", "saint ").replace("st. ", "saint ")
    s = s.replace("&", " and ")
    s = re.sub(r"\s+", " ", s).strip()
    return s

COUNTRY_DATA = [
    ("AF","AFG",["afghanistan"]),
    ("AL","ALB",["albania"]),
    ("DZ","DZA",["algeria"]),
    ("AS","ASM",["american samoa"]),
    ("AD","AND",["andorra"]),
    ("AO","AGO",["angola"]),
    ("AI","AIA",["anguilla"]),
    ("AQ","ATA",["antarctica"]),
    ("AG","ATG",["antigua and barbuda","antigua","barbuda"]),
    ("AR","ARG",["argentina"]),
    ("AM","ARM",["armenia"]),
    ("AW","ABW",["aruba"]),
    ("AU","AUS",["australia"]),
    ("AT","AUT",["austria"]),
    ("AZ","AZE",["azerbaijan"]),
    ("BS","BHS",["bahamas","the bahamas"]),
    ("BH","BHR",["bahrain"]),
    ("BD","BGD",["bangladesh"]),
    ("BB","BRB",["barbados"]),
    ("BY","BLR",["belarus","by"]),
    ("BE","BEL",["belgium"]),
    ("BZ","BLZ",["belize"]),
    ("BJ","BEN",["benin"]),
    ("BM","BMU",["bermuda"]),
    ("BT","BTN",["bhutan"]),
    ("BO","BOL",["bolivia","bolivia plurinational state of","plurinational state of bolivia"]),
    ("BQ","BES",["bonaire sint eustatius and saba","bonaire","sint eustatius","saba"]),
    ("BA","BIH",["bosnia and herzegovina","bosnia","bosnia herzegovina","bih"]),
    ("BW","BWA",["botswana"]),
    ("BV","BVT",["bouvet island"]),
    ("BR","BRA",["brazil"]),
    ("IO","IOT",["british indian ocean territory","chagos"]),
    ("BN","BRN",["brunei","brunei darussalam"]),
    ("BG","BGR",["bulgaria"]),
    ("BF","BFA",["burkina faso"]),
    ("BI","BDI",["burundi"]),
    ("KH","KHM",["cambodia","kampuchea"]),
    ("CM","CMR",["cameroon"]),
    ("CA","CAN",["canada"]),
    ("CV","CPV",["cabo verde","cape verde"]),
    ("KY","CYM",["cayman islands"]),
    ("CF","CAF",["central african republic","car"]),
    ("TD","TCD",["chad"]),
    ("CL","CHL",["chile"]),
    ("CN","CHN",["china","peoples republic of china","prc","mainland china"]),
    ("CX","CXR",["christmas island"]),
    ("CC","CCK",["cocos islands","cocos keeling islands","keeling islands"]),
    ("CO","COL",["colombia"]),
    ("KM","COM",["comoros"]),
    ("CG","COG",["republic of the congo","congo","congo brazzaville"]),
    ("CD","COD",["democratic republic of the congo","dr congo","drc","congo kinshasa"]),
    ("CK","COK",["cook islands"]),
    ("CR","CRI",["costa rica"]),
    ("CI","CIV",["cote d'ivoire","cote divoire","ivory coast"]),
    ("HR","HRV",["croatia"]),
    ("CU","CUB",["cuba"]),
    ("CW","CUW",["curacao"]),
    ("CY","CYP",["cyprus"]),
    ("CZ","CZE",["czechia","czech republic"]),
    ("DK","DNK",["denmark"]),
    ("DJ","DJI",["djibouti"]),
    ("DM","DMA",["dominica"]),
    ("DO","DOM",["dominican republic"]),
    ("EC","ECU",["ecuador"]),
    ("EG","EGY",["egypt"]),
    ("SV","SLV",["el salvador"]),
    ("GQ","GNQ",["equatorial guinea"]),
    ("ER","ERI",["eritrea"]),
    ("EE","EST",["estonia"]),
    ("SZ","SWZ",["eswatini","swaziland"]),
    ("ET","ETH",["ethiopia"]),
    ("FK","FLK",["falkland islands","falklands","islas malvinas","malvinas"]),
    ("FO","FRO",["faroe islands","faeroe islands"]),
    ("FJ","FJI",["fiji"]),
    ("FI","FIN",["finland"]),
    ("FR","FRA",["france"]),
    ("GF","GUF",["french guiana"]),
    ("PF","PYF",["french polynesia"]),
    ("TF","ATF",["french southern territories"]),
    ("GA","GAB",["gabon"]),
    ("GM","GMB",["gambia","the gambia"]),
    ("GE","GEO",["georgia"]),
    ("DE","DEU",["germany"]),
    ("GH","GHA",["ghana"]),
    ("GI","GIB",["gibraltar"]),
    ("GR","GRC",["greece"]),
    ("GL","GRL",["greenland"]),
    ("GD","GRD",["grenada"]),
    ("GP","GLP",["guadeloupe"]),
    ("GU","GUM",["guam"]),
    ("GT","GTM",["guatemala"]),
    ("GG","GGY",["guernsey"]),
    ("GN","GIN",["guinea"]),
    ("GW","GNB",["guinea bissau","guinea-bissau"]),
    ("GY","GUY",["guyana"]),
    ("HT","HTI",["haiti"]),
    ("HM","HMD",["heard island and mcdonald islands"]),
    ("VA","VAT",["holy see","vatican","vatican city"]),
    ("HN","HND",["honduras"]),
    ("HK","HKG",["hong kong","hong kong sar"]),
    ("HU","HUN",["hungary"]),
    ("IS","ISL",["iceland"]),
    ("IN","IND",["india"]),
    ("ID","IDN",["indonesia"]),
    ("IR","IRN",["iran","islamic republic of iran"]),
    ("IQ","IRQ",["iraq"]),
    ("IE","IRL",["ireland"]),
    ("IM","IMN",["isle of man"]),
    ("IL","ISR",["israel"]),
    ("IT","ITA",["italy"]),
    ("JM","JAM",["jamaica"]),
    ("JP","JPN",["japan"]),
    ("JE","JEY",["jersey"]),
    ("JO","JOR",["jordan"]),
    ("KZ","KAZ",["kazakhstan"]),
    ("KE","KEN",["kenya"]),
    ("KI","KIR",["kiribati"]),
    ("KP","PRK",["korea democratic people's republic of","north korea","dprk"]),
    ("KR","KOR",["korea republic of","south korea","republic of korea"]),
    ("KW","KWT",["kuwait"]),
    ("KG","KGZ",["kyrgyzstan","kirgizstan"]),
    ("LA","LAO",["lao people's democratic republic","laos"]),
    ("LV","LVA",["latvia"]),
    ("LB","LBN",["lebanon"]),
    ("LS","LSO",["lesotho"]),
    ("LR","LBR",["liberia"]),
    ("LY","LBY",["libya","libyan arab jamahiriya"]),
    ("LI","LIE",["liechtenstein"]),
    ("LT","LTU",["lithuania"]),
    ("LU","LUX",["luxembourg"]),
    ("MO","MAC",["macao","macau","macao sar"]),
    ("MG","MDG",["madagascar"]),
    ("MW","MWI",["malawi"]),
    ("MY","MYS",["malaysia"]),
    ("MV","MDV",["maldives"]),
    ("ML","MLI",["mali"]),
    ("MT","MLT",["malta"]),
    ("MH","MHL",["marshall islands"]),
    ("MQ","MTQ",["martinique"]),
    ("MR","MRT",["mauritania"]),
    ("MU","MUS",["mauritius"]),
    ("YT","MYT",["mayotte"]),
    ("MX","MEX",["mexico"]),
    ("FM","FSM",["micronesia federated states of","federated states of micronesia"]),
    ("MD","MDA",["moldova","republic of moldova"]),
    ("MC","MCO",["monaco"]),
    ("MN","MNG",["mongolia"]),
    ("ME","MNE",["montenegro"]),
    ("MS","MSR",["montserrat"]),
    ("MA","MAR",["morocco"]),
    ("MZ","MOZ",["mozambique"]),
    ("MM","MMR",["myanmar","burma"]),
    ("NA","NAM",["namibia"]),
    ("NR","NRU",["nauru"]),
    ("NP","NPL",["nepal"]),
    ("NL","NLD",["netherlands","the netherlands","holland"]),
    ("NC","NCL",["new caledonia"]),
    ("NZ","NZL",["new zealand","aotearoa"]),
    ("NI","NIC",["nicaragua"]),
    ("NE","NER",["niger"]),
    ("NG","NGA",["nigeria"]),
    ("NU","NIU",["niue"]),
    ("NF","NFK",["norfolk island"]),
    ("MK","MKD",["north macedonia","macedonia","the former yugoslav republic of macedonia"]),
    ("MP","MNP",["northern mariana islands"]),
    ("NO","NOR",["norway"]),
    ("OM","OMN",["oman"]),
    ("PK","PAK",["pakistan"]),
    ("PW","PLW",["palau"]),
    ("PS","PSE",["state of palestine","palestine","occupied palestinian territory","palestinian territories"]),
    ("PA","PAN",["panama"]),
    ("PG","PNG",["papua new guinea"]),
    ("PY","PRY",["paraguay"]),
    ("PE","PER",["peru"]),
    ("PH","PHL",["philippines","the philippines"]),
    ("PN","PCN",["pitcairn","pitcairn islands"]),
    ("PL","POL",["poland"]),
    ("PT","PRT",["portugal"]),
    ("PR","PRI",["puerto rico"]),
    ("QA","QAT",["qatar"]),
    ("RE","REU",["reunion","reunion island"]),
    ("RO","ROU",["romania"]),
    ("RU","RUS",["russia","russian federation","rf"]),
    ("RW","RWA",["rwanda"]),
    ("BL","BLM",["saint barthelemy","st barthelemy"]),
    ("SH","SHN",["saint helena ascension and tristan da cunha","saint helena","ascension","tristan da cunha"]),
    ("KN","KNA",["saint kitts and nevis","st kitts and nevis","saint kitts","st kitts","nevis"]),
    ("LC","LCA",["saint lucia","st lucia"]),
    ("MF","MAF",["saint martin"]),
    ("PM","SPM",["saint pierre and miquelon"]),
    ("VC","VCT",["saint vincent and the grenadines","st vincent and the grenadines","saint vincent","st vincent","the grenadines"]),
    ("WS","WSM",["samoa"]),
    ("SM","SMR",["san marino"]),
    ("ST","STP",["sao tome and principe","sao tome"]),
    ("SA","SAU",["saudi arabia"]),
    ("SN","SEN",["senegal"]),
    ("RS","SRB",["serbia"]),
    ("SC","SYC",["seychelles"]),
    ("SL","SLE",["sierra leone"]),
    ("SG","SGP",["singapore"]),
    ("SX","SXM",["sint maarten"]),
    ("SK","SVK",["slovakia"]),
    ("SI","SVN",["slovenia"]),
    ("SB","SLB",["solomon islands"]),
    ("SO","SOM",["somalia","somaliland"]),
    ("ZA","ZAF",["south africa"]),
    ("GS","SGS",["south georgia and the south sandwich islands"]),
    ("SS","SSD",["south sudan"]),
    ("ES","ESP",["spain"]),
    ("LK","LKA",["sri lanka"]),
    ("SD","SDN",["sudan"]),
    ("SR","SUR",["suriname"]),
    ("SJ","SJM",["svalbard and jan mayen"]),
    ("SE","SWE",["sweden"]),
    ("CH","CHE",["switzerland"]),
    ("SY","SYR",["syria","syrian arab republic"]),
    ("TW","TWN",["taiwan","taiwan province of china","chinese taipei"]),
    ("TJ","TJK",["tajikistan"]),
    ("TZ","TZA",["tanzania","united republic of tanzania"]),
    ("TH","THA",["thailand"]),
    ("TL","TLS",["timor leste","east timor"]),
    ("TG","TGO",["togo"]),
    ("TK","TKL",["tokelau"]),
    ("TO","TON",["tonga"]),
    ("TT","TTO",["trinidad and tobago"]),
    ("TN","TUN",["tunisia"]),
    ("TR","TUR",["turkiye","turkey"]),
    ("TM","TKM",["turkmenistan"]),
    ("TC","TCA",["turks and caicos islands"]),
    ("TV","TUV",["tuvalu"]),
    ("UG","UGA",["uganda"]),
    ("UA","UKR",["ukraine"]),
    ("AE","ARE",["united arab emirates","uae"]),
    ("GB","GBR",["united kingdom","uk","great britain","england","scotland","wales","northern ireland"]),
    ("US","USA",["united states","united states of america","usa","u s a","u s","u.s","u.s.a","america"]),
    ("UM","UMI",["u s minor outlying islands","united states minor outlying islands"]),
    ("UY","URY",["uruguay"]),
    ("UZ","UZB",["uzbekistan"]),
    ("VU","VUT",["vanuatu"]),
    ("VE","VEN",["venezuela","venezuela bolivarian republic of","bolivarian republic of venezuela"]),
    ("VN","VNM",["viet nam","vietnam"]),
    ("VG","VGB",["virgin islands british","british virgin islands"]),
    ("VI","VIR",["virgin islands u s","u s virgin islands","us virgin islands"]),
    ("WF","WLF",["wallis and futuna"]),
    ("EH","ESH",["western sahara"]),
    ("YE","YEM",["yemen"]),
    ("ZM","ZMB",["zambia"]),
    ("ZW","ZWE",["zimbabwe"]),
    ("XK","XKX",["kosovo"]),
    ("EU","EUR",["european union","eu"]),
]

_NAME_TO_CODE = {}
_ISO3_TO_ISO2 = {}
for iso2, iso3, names in COUNTRY_DATA:
    _ISO3_TO_ISO2[iso3] = iso2
    _NAME_TO_CODE[iso2.lower()] = iso2
    _NAME_TO_CODE[iso3.lower()] = iso2
    for name in names:
        _NAME_TO_CODE[_norm(name)] = iso2

_EXTRA = {
    "czech": "CZ",
    "uk": "GB",
    "u k": "GB",
    "u s": "US",
    "u s a": "US",
    "u s of a": "US",
    "dr congo": "CD",
    "congo kinshasa": "CD",
    "congo brazzaville": "CG",
    "north ireland": "GB",
    "britain": "GB",
    "great britain": "GB",
    "russian fed": "RU",
    "russian federation": "RU",
    "syria": "SY",
    "iran": "IR",
    "kyrgyz republic": "KG",
    "moldova republic of": "MD",
    "macao sar": "MO",
    "hong kong sar": "HK",
}

def country_to_iso2(value: str) -> str | None:
    if not value:
        return None
    v = str(value).strip()
    if re.fullmatch(r"[A-Za-z]{2}", v):
        return v.upper()
    if re.fullmatch(r"[A-Za-z]{3}", v):
        return _ISO3_TO_ISO2.get(v.upper())
    s = _norm(v)
    chunks = re.split(r"[;,/|]", s)
    chunks = [c.strip(" -") for c in chunks if c.strip(" -")]
    chunks = sorted(set(chunks), key=len, reverse=True) or [s]
    for c in chunks:
        if c in _NAME_TO_CODE:
            return _NAME_TO_CODE[c]
        if c in _EXTRA:
            return _EXTRA[c]
    s2 = re.sub(r"\b(the|republic|kingdom|state|states|federation|federal|province|of|and|islamic|arab|bolivarian|people|peoples|democratic|united)\b", " ", s)
    s2 = re.sub(r"\s+", " ", s2).strip()
    if s2 in _NAME_TO_CODE:
        return _NAME_TO_CODE[s2]
    return None
